---
title: "Join"
---

### We are hiring! – Postdoctoral fellow

Aquatic Ecology Lab at University of North Carolina Greensboro is seeking a postdoctoral fellow (the project summary can be found [here](https://nsf.gov/awardsearch/showAward?AWD_ID=2015634&HistoricalAwards=false)). The successful candidate will work with Dr. Akira Terui (UNC Greensboro) and in collaboration with Dr. Jacques Finlay (University of Minnesota). To apply, visit [Spartan Talent](https://spartantalent.uncg.edu/postings/17605) at UNCG. 

**Position summary**: The Post-Doctoral Fellow will work on an NSF-funded project which aims to understand the divers of food chain length in rivers. The project employs advanced mathematical and statistical methods to advance the conceptual understanding of how food chain length is determined in natural systems. Therefore, the postdoc should be proficient in programming, preferably in R and/or C++. The postdoc is expected to communicate his/her results through publications in scientific journals, presentations at professional meetings, and/or outreach events.

**Minimum Qualifications**: Ph.D. in Biology, Ecology, Environmental Science, or related fields.

**Preferable Qualifications**: Proficient in programming, preferably in R and/or C++, with background in stream and food web ecology.

### Undergraduate students

Students who are interested in freshwater ecology/spatial ecology/quantitative ecology are encouraged to contact me (a_terui at uncg.edu). Opportunities exist to learn field research skills and statistical modeling with R.

### Graduate students

The Department of Biology at University of North Carolina at Greensboro (UNCG) offers graduate programs leading to the Master of Science (MS) in Biology and Doctor of Philosophy (PhD) in Environmental Health Science degrees. Aquatic ecology lab at UNCG is currently looking for a master student starting Fall 2021. The student will work on the statistical modelling of discharge variation in relation to land use and geometries of river networks. The project leverages the public database of discharge and land use. This is part of the project exploring drivers of food chain length in rivers and the student is expected to work collaboratively with current lab members. The student is expected to have a solid understanding in ecology, environmental science, hydrology or related fields. Advanced skills in R and GIS are a big plus.

If interested, please contact me (a_terui at uncg.edu) with (1) your CV, (2) a one-page research statement describing your previous research experiences and interests, and (3) the names and contacts of three referees. Review of applications begins immediately. The departmental deadline for submitting the application to the graduate studies is April 1, 2021. If the student is accepted into the graduate program, there is the possibility for financial support in the form of teaching or research assistantships. For details, please visit [here](https://biology.uncg.edu/graduate/apply/)

### Postdocs

I welcome inquiries about postdoctoral projects in our research group. If our research program is a good fit for your interests, please email me (a_terui at uncg.edu) with your CV and a short summary of your research interests (1-2 pages). We can develop collaborative projects through postdoctoral fellowships, such as [Smith Fellowship](https://conbio.org/mini-sites/smith-fellows) and JSPS Postdoctoral Fellowship.